# -*- coding: utf-8 -*-
"""coding_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4pGumt1jziPdrTSn9Z20i497mMGf2zr
"""

prices = [7, 1, 5, 3, 6, 4]

def max_profit(prices):
  profit = 0
  for i in range(1, len(prices)):
    transaction = prices[i] - prices[i-1]
    if transaction > 0:
      profit += transaction
  return profit
  
max_profit(prices)